name: Build plugin pre-release

on:
  release:
    types: [ prereleased ]

jobs:
  build:
    name: Build plugin asset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Generate plugin asset
        run: |
          mkdir -p release/host-analyticsjs-local
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/host-analyticsjs-local/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/host-analyticsjs-local.zip" .

      - name: Attach asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/host-analyticsjs-local.zip
          asset_name: host-analyticsjs-local.zip
          asset_content_type: application/zip
